services:
  movie-service:
    build: ./services/movie-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/marvel
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis

#  user-service:
#    build: ./services/user-service
#    ports:
#      - "3001:3000"
#    environment:
#      - MONGO_URI=mongodb://mongo:27017/marvel
#      - REDIS_HOST=redis
#      - REDIS_PORT=6379
#    depends_on:
#      - mongo
#      - redis

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

volumes:
  mongo-data:
